### ISSUE TITLE
KeyError: 'upload'，创建app不成功

### ISSUE THREAD

**Issue by aigcun** [xingren23/ComfyFlowApp#61]
2024-02-14 15:47:19.643 Uncaught app exception
Traceback (most recent call last):
  File "D:\anaconda3\envs\comfyflowapp\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 530, in _run_script
    self._session_state.on_script_will_rerun(rerun_data.widget_states)
  File "D:\anaconda3\envs\comfyflowapp\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 61, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
  File "D:\anaconda3\envs\comfyflowapp\Lib\site-packages\streamlit\runtime\state\session_state.py", line 500, in on_script_will_rerun
    self._call_callbacks()
  File "D:\anaconda3\envs\comfyflowapp\Lib\site-packages\streamlit\runtime\state\session_state.py", line 513, in _call_callbacks
    self._new_widget_state.call_callback(wid)
  File "D:\anaconda3\envs\comfyflowapp\Lib\site-packages\streamlit\runtime\state\session_state.py", line 260, in call_callback
    callback(*args, **kwargs)
  File "D:\Git\ComfyFlowApp\modules\new_app.py", line 276, in submit_app
    app_config = gen_app_config()
                 ^^^^^^^^^^^^^^^^
  File "D:\Git\ComfyFlowApp\modules\new_app.py", line 241, in gen_app_config
    node_id, param, input_param1_inputs = get_node_input_config(
                                          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\ComfyFlowApp\modules\new_app.py", line 155, in get_node_input_config
    if isinstance(class_input[param][0], str):
                  ~~~~~~~~~~~^^^^^^^
KeyError: 'upload'

工作流在本地comfyui里运行正常的，
comfyflowapp也安装正常，但创建不成功。报错如上。

**Comment by aigcun** [comment]
难道用到的自定义节点还要另外配置吗，应该怎么配置，如何解决？谢谢！

**Comment by Sheng-Charles** [comment]
相同的情况

**Comment by xingren23** [comment]
there might be problems with parsing some nodes, which workflow can be used to reproduce this issue, i will try it out 
@aigcun @Sheng-Charles post the image(include workflow) here.
